spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ticket
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: 127.0.0.1
      port: 6379